---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024
    cpus: 4

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
- name: centos-6.3
- name: centos-5.8

suites:
- name: default
  run_list:
  - recipe[shinken]
- name: package
  run_list:
  - recipe[shinken]
  attributes:
    shinken:
      install_method: package
- name: binary
  run_list:
  - recipe[shinken]
  attributes:
    shinken:
      install_method: binary
